services:
  hornbill-app-preprod:
    image: 423671572921.dkr.ecr.eu-west-3.amazonaws.com/hornbill-app-docker-repo:${IMAGE_VERSION}
    container_name: hornbill-app-preprod
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - hornbill-network-preprod
      - nginx-package-manager_proxy-network

networks:
  hornbill-network-preprod:
    external: true
  nginx-package-manager_proxy-network:
    external: true
