services:
  hornbill-api-prod:
    image: 423671572921.dkr.ecr.eu-west-3.amazonaws.com/hornbill-api-docker-repo:${IMAGE_VERSION}
    container_name: hornbill-api-prod
    environment:
      - NODE_ENV=production
    networks:
      - hornbill-network-prod

networks:
  hornbill-network-prod:
    external: true
