services:
  hornbill-api-preprod:
    image: 423671572921.dkr.ecr.eu-west-3.amazonaws.com/hornbill-api-docker-repo:${IMAGE_VERSION}
    container_name: hornbill-api-preprod
    environment:
      - NODE_ENV=production
    networks:
      - hornbill-network-preprod

networks:
  hornbill-network-preprod:
    external: true
