services:
  hornbill-api-preprod:
    image: 423671572921.dkr.ecr.eu-west-3.amazonaws.com/hornbill-api-docker-repo:${IMAGE_VERSION}
    container_name: hornbill-api-preprod
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - hornbill-network-preprod
      - nginx-package-manager_proxy-network

  hornbill-database-preprod:
    container_name: hornbill-database-preprod
    image: postgres:15
    env_file: .env
    volumes:
      - ${DATABASE_DATA_PATH}:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - hornbill-network-preprod

networks:
  hornbill-network-preprod:
    external: true
  nginx-package-manager_proxy-network:
    external: true
